### PR TITLE
rerendered

### PR DESCRIPTION
**Pull request by doutriaux1**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@conda-forge-admin why is only one check triggered? Why haven't the files uploaded after master passed (which is why I'm trying to rerender)

**Comment by doutriaux1** [comment]
@conda-forge-admin apparently the rerender disabled mac, linux and windows! Any option I need to pass to rerender?

**Comment by CJ-Wright** [comment]
Out of curiosity why is this skipping python, is python installed?

**Comment by doutriaux1** [comment]
@CJ-Wright if I recall . correctly (at least up until version 18.0) Python3 was failing somePy2 syntax left in installer.

**Comment by CJ-Wright** [comment]
Ah if there is python syntax in the installer then you most likely need python in the build dependencies.

**Pull request closed without merging**
