### PR TITLE
Use compiler syntax

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by jschueller** [comment]
@doutriaux1 I figured why no binary was built: it was skipped after rerendering, this fixes the package

**Comment by jschueller** [comment]
@conda-forge/mesalib I had to go back to v17.3.9, 18.x series wont build on osx, but as no 18.x binary has been published it is ok, care to merge ?

**Comment by jschueller** [comment]
could someone from @conda-forge/core merge this ?

**Comment by scopatz** [comment]
@dnadeau4 @doutriaux1 @sankhesh @danlipsa - are any of you able to review this please?

**Pull request merged**
