### PR TITLE
Disable software driver and remove GL.so (And other related libraries)

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
This seems to alleviate the software rendering issues on my local machine. SInce I assume that this issue will only proliferate, I would like to merge this ASAP. @conda-forge/mesalib if somebody would have time to review it would be greatly appreciated.

I don't think anybody wants "software" rending. We should consider previous builds a mistake IMO.

**Review by matthiasdiener — APPROVED** [review]

**Comment by hmaarrfk** [comment]
Are you OK with adding `automerge` @matthiasdiener

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by matthiasdiener** [comment]
> Are you OK with adding `automerge` @matthiasdiener

Yeah, I think that's fine

**Pull request merged**
