### PR TITLE
18.0.0 and aarch

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes #23 #21 #14 #24 

osx is built with 10.12 to have clock gettime
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@hmaarrfk thank you for this, please add yourself as developer so you can merge in the future. I'm no longer involved in this project. @muryanto1 amd @downiec please add yourselves as well as developpers in a PR I will merge it.

**Comment by hmaarrfk** [comment]
thansk i added myself.

**Comment by muryanto1** [comment]
@hmaarrfk do you mind if I add myself as a maintainer to this PR? or if you can add "muryanto1" to the list of maintainers? Thank you!!

**Comment by downiec** [comment]
@hmaarrfk, @muryanto1  if I could be added as maintainer as well, that would be great!

**Comment by hmaarrfk** [comment]
thanks all !

**Comment by muryanto1** [comment]
@hmaarrfk @doutriaux1  Hi Mark, I tried the osx build:
mesalib                   18.0.0               hb6cfc13_0    conda-forge

when I did my plot() routine, my MacOS is spinning, and my plot() routine never returned.
I tried it both on my MacOS laptop and in CircleCI.
I have yet to try the Linux build.

**Comment by hmaarrfk** [comment]
hmmm which one of your packages is using mesalib?

**Comment by hmaarrfk** [comment]
it could be that 18.0 is rather old, therei s probably a patch release we should release. could you open a new issue?

**Comment by hmaarrfk** [comment]
its probably because your OS version is smaller than 10.12.

I thought conda was taking care of that now.

@conda-forge/core is there a way to specify the minimum OSX version in the conda-yaml file?

**Comment by beckermr** [comment]
You can put a virtual package constraint in the recipe itself. I forget exactly how it works.

cc @msarahan @jjhelmus for guidance

I think it is something like

```yaml
requirements:
  run:
    - __osx >=10.2
```

**Comment by isuruf** [comment]
See the docs https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

**Comment by beckermr** [comment]
Ahh good call! I was close!

**Comment by hmaarrfk** [comment]
thanks all!

**Pull request merged**
