### PR TITLE
Use gcc from the container

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@isuruf why do you prefer to use the container's gcc rather than the conda one? Does that introduces risks of incompatibility on some newer systems?

**Comment by isuruf** [comment]
I was trying to use mesalib at https://github.com/conda-forge/paraview-feedstock/pull/2 and it failed because the `paraview` recipe was using the container's gcc which is older than what this package was compiled with.

**Comment by doutriaux1** [comment]
@isuruf I'm ok to merge this in , you should probably update the build number on it though. Also it if turns out it breaks our software I would have to revert this pronto. Maybe we could trigger a rebuild on paraview? So they use the same newer gcc?

**Comment by isuruf** [comment]
Yeah, I have a PR in paraview that uses the newer conda package that works fine.

**Pull request closed without merging**
