### PR TITLE
Update to latest

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by doutriaux1** [comment]
@jschueller should we merge this in?

**Comment by jschueller** [comment]
Yes

**Comment by doutriaux1** [comment]
@jschueller it's merged and "greened" shouldn't the files appear at: https://anaconda.org/conda-forge/mesalib/files

**Comment by jschueller** [comment]
Yup, something's wrong.

**Comment by jschueller** [comment]
@conda-forge/core something wrong here, packages were not uploaded

**Comment by doutriaux1** [comment]
@conda-forge/core rerender made things worse, see: https://github.com/conda-forge/mesalib-feedstock/pull/14

**Pull request merged**
