### PR TITLE
DEV: Update to 20.1.4.rc1

### PR DESCRIPTION
**Pull request by jasonb5**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jasonb5** [comment]
@conda-forge-admin, please rerender

**Comment by jasonb5** [comment]
@conda-forge-admin, please rerender

**Comment by jasonb5** [comment]
Disabled aarch64 and ppc64le, missing dependency for `libdrm` for those platforms.

**Comment by wolfv** [comment]
I have just added libdrm to the migrations. anything else that has to be considered, here?

**Comment by wolfv** [comment]
note afaik the latest version is 20.2.0 now

**Comment by wolfv** [comment]
https://github.com/conda-forge/libdrm-feedstock/pull/8

**Comment by matthiasdiener** [comment]
Superseded by #34.

**Pull request closed without merging**
